[[intro]]
== Introduction

The Zalasr (Load-Acquire and Store-Release) extension provides load-acquire and store-release instructions in RISC-V.
These can be important for high performance designs by enabling finer-grained synchronisation than is possible with fences alone, by providing a unidirectional fence.
Load-acquire and store-release are widely used in language-level memory models:
both the Java and {cpp} memory models make use of acquire-release semantics, and {cpp}'s `atomic` provides primitives that are meant to map directly to load-acquire and store-release instructions.

The Zalasr extension builds on the atomic support provided by the Zaamo (Atomic Memory Operations), Zalrsc (Load-Reserved and Store-Conditional), and Zabha (Byte and Halfword Atomic Memory Operations) extensions by providing additional atomic operations (although it can be implemented independently of them).
All of the AMO operations in Zaamo (and Zabha) are read-modify-write operations that both load and store.
The Zalrsc extension provides operations that are only loads or stores.
However, since it is designed to perform an atomic operation on a single memory word or doubleword, the loads and stores are designed to be paired.
The load-reserved implies that a future store-conditional will follow while store-conditional requires that there was a previous load-reserved without other intervening loads or stores.
Therefore, the Zalrsc extension does not provide a general atomic and ordered load or store.

Zalasr fills this gap by offering truly standalone atomic and ordered loads and stores.
The Zalasr instructions are atomic loads and stores that support ordering annotations.
With the combination of Zaamo, Zabha, and Zalasr all {cpp} atomic operations can be supported with single instructions.